x-common: &common
  build: .
  env_file: .env
  depends_on:
    cache:
      condition: service_healthy

services:
  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    restart: unless-stopped

  fastapi:
    <<: *common
    command: gunicorn app.main:app -c gunicorn.conf.py
    restart: unless-stopped

  celery:
    <<: *common
    command: celery -A app.backend.celery worker --loglevel=info
    restart: on-failure

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 3

volumes:
  redis_data:
