"""review unique constraint added

Revision ID: 7f4cfbc508bf
Revises: 7e307609e920
Create Date: 2025-05-31 21:02:21.822913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4cfbc508bf'
down_revision: Union[str, None] = '7e307609e920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_user_id_product_id', 'review', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_user_id_product_id', 'review', type_='unique')
    # ### end Alembic commands ###
