"""add category & product

Revision ID: a8329b161836
Revises: 
Create Date: 2025-05-26 18:19:18.478600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8329b161836'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.category_id'], name=op.f('fk_category_parent_id_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('product',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name=op.f('fk_product_category_id_category')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
